services:
  db:
    image: postgres:15.3
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: eventos
    ports:
      - "5432:5432"

volumes:
  postgres_data: